name: Build Geode Mod
on: [push, workflow_dispatch]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          cache: false
